### ISSUE TITLE
Add option to change dialog element

### ISSUE THREAD

**Issue by Ciloe** [hata6502/editorjs-layout#31]
H! there !

Is it possible to add an option to set the dialog elements ? For example to add a div instead of dialog ?

The problem is that with dialog, any new modals with z-index can't go above the dialog html element. We can't use bootstrap modals or other libraries....

Many thanks !

**Comment by hata6502** [comment]
Sorry!, but I won't add the option to change dialog element.
I recommend to fork this repository and customize it.
